name: New Issue
description: Submit a new issue to help us improve.
title: "[Docs]: "
labels: ["Documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submiting this issue!
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Please provide a description of the problem.
    validations:
      required: true
    - type: textarea
    id: description
    attributes:
      label: Prposed Issue Solution
      description: Please provide a description of how the problem can be solved.
    validations:
      required: true
    - type: dropdown
    id: version
    attributes:
      label: Affected Component
      description: If applicable, provide the component relevant to this issue.
      options:
        - CSIT
        - Directory
        - Identity
        - OASF
        - SLIM
        - Other
      default: 0
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: By submitting this issue, you agree to the following
      options:
        - label: I have read the [contributing guidelines](/agntcy/repo-template/blob/main/CONTRIBUTING.md).
          required: true
        - label: I have verified this does not duplicate an existing issue.
          required: true
